### ISSUE TITLE
error opening in page

### ISSUE THREAD

**Issue by ramilkamal** [Archakov06/react-pizza-v2#2]
(error react-router-dom)
вегетарянская, гриль, острые, закрытые, это страницы не открываеться
![1](https://user-images.githubusercontent.com/89657343/189480297-aeb83d3c-d9f1-45f3-8604-cb47e9b66631.png)

**Comment by kamalovvvv** [comment]
> (error react-router-dom) вегетарянская, гриль, острые, закрытые, это страницы не открываеться
![Снимок](https://user-images.githubusercontent.com/89657343/189387410-9e91569c-e9ca-4675-84a7-39d2ddc1f7c4.PNG)
